# Generated by Django 4.0.5 on 2022-07-24 07:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_due',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 7, 8, 29, 675716, tzinfo=utc)),
        ),
    ]
