# Generated by Django 4.0.5 on 2022-07-24 07:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_task_date_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_due',
            field=models.DateField(default=datetime.datetime(2022, 7, 24, 7, 11, 44, 160702, tzinfo=utc)),
        ),
    ]
