# Generated by Django 4.0.5 on 2022-07-24 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_task_date_due'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
