# Generated by Django 4.0.5 on 2022-07-24 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='content',
        ),
    ]
