# Generated by Django 4.0.5 on 2022-07-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_remove_task_completed_habits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habits',
            old_name='name',
            new_name='habit',
        ),
    ]
